### ISSUE TITLE
[Placeholder] Sorry! Something went wrong.

### ISSUE THREAD

**Issue by SmartBoy84** [seia-soto/outline-server-multiarch#9]
I know way too little with how bash works but exporting the `SB_IMAGE` env var separately before running the command doesn't seem to work as the script fails with `Sorry! Something went wrong.`  
However, `SB_IMAGE=ghcr.io/seia-soto/shadowbox:latest sudo --preserve-env bash -c ./install_server.sh` worked for me.

Thank you for this (issue was kind of an excuse to say this lmao)

**Comment by seia-soto** [comment]
I don't have enough resource to test the full deployment yet due to some high load task now but `export` seems working as expected.

There's nothing useful as I can see now, but I expect that it can be related to environmental specific problem such as shell you're using or pre-existing image in same name.

I'll test further when I can allocate some computational resource here.

```bash
Last login: Thu Jun  1 08:25:56 on ttys004

~
% export TEST_AA=1                                                 

~
% echo 'echo $TEST_AA' | bash
1
```

**Comment by seia-soto** [comment]
# Possible troubleshootings

For someone visited this page due to the error above, please try one of followings manually:

## Adding `sudo` or running as `root`

```
# master release, updated daily (might fail sometime)
export SB_IMAGE="ghcr.io/seia-soto/shadowbox:master"

# stable release, NOT MORE UPDATED (It is for outline-server v1.9 or lower, use `latest` instead)
export SB_IMAGE="ghcr.io/seia-soto/shadowbox:release"

# latest release, updated irregularly
export SB_IMAGE="ghcr.io/seia-soto/shadowbox:latest"

curl -sL "https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh" | sed '/local MACHINE_TYPE/,/fi/{d}' | sudo --preserve-env bash
```

## Manually populating the environment variables

This answer is based on @SmartBoy84 's solution and will create a file called `script.sh` in the same directory of shell's working directory.

```bash
curl -sL "https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh" | sed '/local MACHINE_TYPE/,/fi/{d}' > ./install_server.sh

SB_IMAGE=ghcr.io/seia-soto/shadowbox:latest sudo --preserve-env bash -c ./install_server.sh
```

**Comment by SmartBoy84** [comment]
It seems env can be separately set but bash needs to be run with `--preserve-env` flag on the pi  
So maybe just change `| bash` to `| sudo --preserve-env bash` in the README?

**Comment by seia-soto** [comment]
Thanks @SmartBoy84 for pointing out, I updated the comment.
